name: build

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    - name: Set up CMake
      if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: lukka/get-cmake@v2

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build